#!/bin/bash
set -eu

if [ $# -ne 1 ]; then
    echo "Usage: $0 capturesDir"
    exit 1
fi

CAPDIR=$1

# Get last capture
# NOTE: Assumes filenames are in motion command's default format, e.g. 01-20150621183214-02.jpg
CAPFILE=$(ls $CAPDIR | tail -1)
if [ -n "$CAPFILE" ]; then
    CAPTIME=`date -r "$CAPDIR/$CAPFILE"`
    echo "Last motion was $CAPDIR/$CAPFILE captured at $CAPTIME"

    # Remove all other captures
    ls -d $CAPDIR/* | head -n -1 | xargs --null -r -d "\n" rm
else
    echo "No captures found in $CAPDIR"
fi
