#!/bin/bash
set -eu

CAPDIR="./captures"
UPDINT=3

while true; do
    sleep $UPDINT

    # Get last capture
    CAPFILE=`ls -t $CAPDIR | head -1`
    if [ -n "$CAPFILE" ]; then
        CAPTIME=`date -r "$CAPDIR/$CAPFILE"`
        echo "Last motion was captured at $CAPTIME"

        # Remove all other captures, assumes filenames have no newlines
        ls -dt $CAPDIR/* | tail -n +2 | xargs --null -r -d "\n" rm

        # Update site if necessary
    else
        echo "No captures found in $CAPDIR"
    fi
done
