#!/bin/bash
set -o nounset

CAPDIR="./captures"
UPDINT=3

while true; do
    sleep $UPDINT

    # Get last capture
    CAPFILE=`ls -t $CAPDIR | head -1`
    CAPTIME=`date -r "$CAPDIR/$CAPFILE"`
    echo "Last motion was captured at $CAPTIME"

    # Update site if necessary
done
