#!/bin/bash
# Prevent use of uninitialized variables
set -o nounset

LCK='./.eventStarted.lck';
# Open lock file with unused file descriptor
eval "exec {HND}<> $LCK;"; || { echo "Failed to open lock file with $?"; exit 1; } 
# Always close the lock file
trap "exec $HND>&-" INT TERM EXIT 
echo "Opened $LCK with descriptor $HND"

if flock -n $HND; then 
    # Replace old PID
    > $LCK; 
    echo $$ >> ./.eventStarted.lck;
    echo "Handling event in this process ($$)";

    # Keep updating the site while we see motion
    # When the motion event ends, we will kill this process
    while (1)
    {
        sleep 10;
        # Get latest capture, update site, delete all captures
    }
else
    echo "Process $(cat $LCK) is already handling event start";
fi
