#!/bin/bash
set -eu

if [ $# -ne 2 ]; then
    echo "Usage: $0 capturesDirAbs updateInterval"
    exit 1
fi

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
UPDINT=$2

while true; do
    sleep $UPDINT
    LASTCAP=$(python $SCRIPTDIR/checkLastCapture.py $1)
    if [ -n "$LASTCAP" ]; then
        ruby updateSite.rb
    fi
done
