#!/bin/bash
set -eu

if [ $# -ne 2 ]; then
    echo "Usage: $0 capturesDirAbs updateInterval"
    exit 1
fi

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
UPDINT=$2

while true; do
    sleep $UPDINT
    LASTCAPDETAILS=$(python $SCRIPTDIR/getLastCapture.py $1)
    if [ -n "$LASTCAPDETAILS" ]; then
        ruby updateSite.rb $LASTCAPDETAILS
        # Optimize here, store LASTCAP
    fi
done
